name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test_wrapper:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt
      - name: Run tests
        run: python Backend/wrapper_test.py 
